version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/go/src/app
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DBNAME: $POSTGRES_DBNAME
      POSTGRES_SSLMODE: $POSTGRES_SSLMODE
      POSTGRES_TIMEZONE: $POSTGRES_TIMEZONE
  db:
    container_name: db
    image: postgres:15.2-alpine
    ports:
      - "5433:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DBNAME
      TZ: $POSTGRES_TIMEZONE
