version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./app:/go/src/app
    ports:
      - 8080:8080
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
